# Generated by Django 2.0.6 on 2018-07-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180705_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.CharField(default='7vQaSEw2qlWE', max_length=12),
        ),
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='books/%Y/%m/%d/'),
        ),
    ]
